# Generated by Django 3.2.3 on 2021-07-20 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_workexperience_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workexperience',
            name='end_time',
            field=models.DateField(blank=True, null=True),
        ),
    ]
