# Generated by Django 3.2.3 on 2021-07-23 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('Personal Skil', 'Personal Skil'), ('Hard Skil', 'Hard Skil')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
